Repository devridge-team-project/devridge-server, pull requests merged in 2024-04, with the labels that each got.

#119 프로젝트 API를 구현합니다.
  api-module/src/main/java/org/devridge/api/application/community/project/ProjectCommentLikeDislikeMapper.java
  api-module/src/main/java/org/devridge/api/application/community/project/ProjectCommentLikeDislikeService.java
  api-module/src/main/java/org/devridge/api/application/community/project/ProjectCommentMapper.java
  api-module/src/main/java/org/devridge/api/application/community/project/ProjectCommentService.java
  api-module/src/main/java/org/devridge/api/application/community/project/ProjectLikeDislikeMapper.java
  api-module/src/main/java/org/devridge/api/application/community/project/ProjectLikeDislikeService.java
  api-module/src/main/java/org/devridge/api/application/community/project/ProjectMapper.java
  api-module/src/main/java/org/devridge/api/application/community/project/ProjectScrapMapper.java
  api-module/src/main/java/org/devridge/api/application/community/project/ProjectScrapService.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/request/ProjectCommentRequest.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/ProjectCommentResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/ProjectComment.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/ProjectCommentLikeDislike.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/ProjectLikeDislike.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/ProjectScrap.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/id/ProjectCommentLikeDislikeId.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/id/ProjectLikeDislikeId.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/id/ProjectScrapId.java
  api-module/src/main/java/org/devridge/api/infrastructure/community/project/ProjectCommentLikeDislikeRepository.java
  api-module/src/main/java/org/devridge/api/infrastructure/community/project/ProjectCommentQuerydslRepository.java
  api-module/src/main/java/org/devridge/api/infrastructure/community/project/ProjectCommentRepository.java
  api-module/src/main/java/org/devridge/api/infrastructure/community/project/ProjectLikeDislikeRepository.java
  api-module/src/main/java/org/devridge/api/infrastructure/community/project/ProjectRepository.java
  api-module/src/main/java/org/devridge/api/infrastructure/community/project/ProjectScrapRepository.java
  api-module/src/main/java/org/devridge/api/presentation/controller/community/project/ProjectCommentController.java
  api-module/src/main/java/org/devridge/api/presentation/controller/community/project/ProjectCommentLikeDislikeController.java
  api-module/src/main/java/org/devridge/api/presentation/controller/community/project/ProjectLikeDislikeController.java
  api-module/src/main/java/org/devridge/api/presentation/controller/community/project/ProjectScrapController.java
Labels: 기능 구현 ✨

#124 자유게시글 댓글 목록이 조회되지 않는 오류를 수정합니다.
  api-module/src/main/java/org/devridge/api/infrastructure/community/freeboard/CommunityCommentQuerydslReopsitory.java
Labels: 오류 해결❗️

#133 study 전체 목록 조회 api 반환 변수명을 수정합니다.
  api-module/src/main/java/org/devridge/api/application/community/study/StudyMapper.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/StudyListResponse.java
Labels: 리팩토링 🛠️

#136 커뮤니티 API의 전반적인 코드 리팩토링을 진행합니다.
  api-module/src/main/java/org/devridge/api/application/community/project/ProjectMapper.java
  api-module/src/main/java/org/devridge/api/application/community/project/ProjectService.java
  api-module/src/main/java/org/devridge/api/application/community/study/StudyMapper.java
  api-module/src/main/java/org/devridge/api/application/community/study/StudyService.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/request/StudyRequest.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/CommunitySliceResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/ProjectDetailResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/ProjectListResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/StudyDetailResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/StudyListResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/Study.java
  api-module/src/main/java/org/devridge/api/infrastructure/community/project/ProjectQuerydslRepository.java
Labels: 리팩토링 🛠️, 오류 해결❗️

#138 Access, Refresh token 모두 쿠키로 통신하도록 변경합니다.
  api-module/src/main/java/org/devridge/api/application/auth/AuthService.java
  api-module/src/main/java/org/devridge/api/application/auth/SocialLoginService.java
  api-module/src/main/java/org/devridge/api/common/security/filter/JwtAuthenticationFilter.java
  api-module/src/main/java/org/devridge/api/common/security/filter/JwtAuthorizationFilter.java
  api-module/src/main/java/org/devridge/api/common/util/AccessTokenUtil.java
  api-module/src/main/java/org/devridge/api/common/util/JwtUtil.java
  api-module/src/main/java/org/devridge/api/common/util/RefreshTokenUtil.java
  api-module/src/main/java/org/devridge/api/presentation/controller/auth/SocialLoginController.java
Labels: 기능 구현 ✨

#144 해시태그 관련 데이터 및 로직을 삭제합니다.
  api-module/src/main/java/org/devridge/api/application/community/freeboard/CommunityHashtagService.java
  api-module/src/main/java/org/devridge/api/application/community/freeboard/CommunityMapper.java
  api-module/src/main/java/org/devridge/api/application/community/freeboard/CommunityService.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/request/CreateCommunityRequest.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/CommunityDetailResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/CommunitySliceResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/HashtagResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/Community.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/CommunityHashtag.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/Hashtag.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/id/CommunityHashtagId.java
  api-module/src/main/java/org/devridge/api/infrastructure/community/freeboard/CommunityHashtagRepository.java
  api-module/src/main/java/org/devridge/api/infrastructure/community/freeboard/CommunityQuerydslRepository.java
  api-module/src/main/java/org/devridge/api/infrastructure/community/hashtag/HashtagRepository.java
  api-module/src/main/java/org/devridge/api/presentation/controller/community/freeboard/CommunityController.java
  api-module/src/main/java/org/devridge/api/presentation/controller/community/freeboard/CommunityHashtagController.java
Labels: 리팩토링 🛠️

#146 커뮤니티에 해당하는 게시글 상세조회 api의 응답dto에 scrap수와 comment수를 추가합니다.
  api-module/src/main/java/org/devridge/api/application/community/freeboard/CommunityMapper.java
  api-module/src/main/java/org/devridge/api/application/community/project/ProjectMapper.java
  api-module/src/main/java/org/devridge/api/application/community/study/StudyMapper.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/CommunityDetailResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/ProjectDetailResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/StudyDetailResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/Project.java
  api-module/src/main/java/org/devridge/api/domain/community/entity/Study.java
Labels: 리팩토링 🛠️
