Repository devridge-team-project/devridge-server, pull requests merged in 2024-02, with the labels that each got.

#54 Community의 ResponseDto 반환 형식을 리팩토링합니다
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/CommunityCommentResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/CommunityDetailResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/dto/response/MemberInfoResponse.java
  api-module/src/main/java/org/devridge/api/domain/community/mapper/CommunityCommentMapper.java
  api-module/src/main/java/org/devridge/api/domain/community/mapper/CommunityMapper.java
Labels: 리팩토링 🛠️

#60 멤버 도메인에 프로필 이미지를 사용하는 기능을 추가합니다.
  api-module/src/main/java/org/devridge/api/domain/member/controller/MemberController.java
  api-module/src/main/java/org/devridge/api/domain/member/dto/request/CreateMemberRequest.java
  api-module/src/main/java/org/devridge/api/domain/member/dto/request/UpdateMemberProfileRequest.java
  api-module/src/main/java/org/devridge/api/domain/member/dto/request/UpdateProfileRequest.java
  api-module/src/main/java/org/devridge/api/domain/member/entity/Member.java
  api-module/src/main/java/org/devridge/api/domain/member/repository/MemberRepository.java
  api-module/src/main/java/org/devridge/api/domain/member/service/MemberService.java
  api-module/src/main/java/org/devridge/api/domain/s3/validator/type/ImagePath.java
  api-module/src/main/resources/application.yml
  common-module/src/main/java/org/devridge/common/entity/BaseEntity.java
Labels: 기능 구현 ✨, 리팩토링 🛠️

#61 JWT 토큰 교환 로직을 변경합니다.
  api-module/src/main/java/org/devridge/api/security/filter/JwtAuthenticationFilter.java
  api-module/src/main/java/org/devridge/api/security/filter/JwtAuthorizationFilter.java
  api-module/src/main/java/org/devridge/api/security/handler/CustomLogoutHandler.java
  api-module/src/main/java/org/devridge/api/util/JwtUtil.java
Labels: 기능 구현 ✨
